(function(){
'use strict';
const X=window.OzonXlsx,N=window.OzonV2Normalize,A=window.OzonV2,F=window.OzonV2UiFormat;
const $=id=>document.getElementById(id);
const state={campaigns:new Map(),files:[],sourceOrder:0,analysis:[],selected:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString('ru-RU',{maximumFractionDigits:2}):'—';
const cpcMoney=n=>F.cpc(n);
const pct=n=>Number.isFinite(Number(n))?(Number(n)*100).toLocaleString('ru-RU',{maximumFractionDigits:1})+'%':'—';
const prob=n=>Number.isFinite(Number(n))?(Number(n)<.001?'<0,001':Number(n).toLocaleString('ru-RU',{minimumFractionDigits:3,maximumFractionDigits:3})):'—';
const dateRu=s=>s?String(s).split('-').reverse().join('.'):'—';
function isoToday(){const d=new Date(),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function setStatus(text,kind=''){const e=$('status');e.textContent=text;e.className='status '+kind}
function mergeRows(rows){for(const r of rows){if(!state.campaigns.has(r.campaignId))state.campaigns.set(r.campaignId,new Map());const m=state.campaigns.get(r.campaignId),key=`${r.date}|${r.sku}`,old=m.get(key);if(!old||r.sourceOrder>=old.sourceOrder)m.set(key,r)}}
function currentRows(){const id=$('campaignSelect').value,m=state.campaigns.get(id);return m?[...m.values()]:[]}
function refreshCampaigns(){const s=$('campaignSelect'),old=s.value;s.innerHTML=[...state.campaigns.keys()].sort().map(id=>`<option value="${esc(id)}">РК ${esc(id)}</option>`).join('');if(old&&state.campaigns.has(old))s.value=old}
function renderFiles(){$('fileList').innerHTML=state.files.map(f=>`<span class="chip">${esc(f.name)} · РК ${esc(f.campaignId)} · ${f.rows} строк</span>`).join('')}
async function ingest(files){if(!files?.length)return;setStatus('Читаю XLSX…');for(const file of files){try{const parsed=await X.readOzonWorkbook(await file.arrayBuffer());state.sourceOrder++;const campaignId=parsed.campaignId||`FILE-${state.sourceOrder}`;const rows=N.normalizeOzonRows(parsed.rows,campaignId,state.sourceOrder);mergeRows(rows);state.files.push({name:file.name,campaignId,rows:rows.length})}catch(e){setStatus(`${file.name}: ${e.message}`,'error');return}}renderFiles();refreshCampaigns();setStatus(`Загружено файлов: ${state.files.length}`,'ok');analyze()}
function settings(){const mde=(Number($('mdePct').value)||20)/100,maxDays=Number($('maxTestDays').value)||28,minCpc=(Number($('minCpcChange').value)||5)/100,unit=Number($('unitContribution').value),margin=Number($('marginPct').value);const economics={};if(unit>0)economics.unitContributionBeforeAds=unit;if(margin>=0&&$('marginPct').value!=='')economics.contributionMarginRate=margin/100;return{todayIso:isoToday(),cpc:{minRelativeChange:minCpc,minDays:4,noiseMultiplier:2.5},budget:{minRollingPoints:5},price:{minCoverage:.7,stableTolerance:.02},transitions:{priceChangeTolerance:.03,budgetCeilingTolerance:.15},economics,power:{mdeRelative:mde,maxTestDays:maxDays,alpha:.05,power:.80},evaluator:{mdeRelative:mde,maxTestDays:maxDays},temporal:{lags:[0,1,2],signEpsilon:.02,maxLagSpread:.25},uncertainty:{reps:400,alpha:.05,seed:20260828},fdrAlpha:.05,planner:{mdeRelative:mde,maxTestDays:maxDays,minRelativeChange:minCpc,defaultStep:.05,maxStep:.15,noiseMultiplier:2.5,stabilizationDays:2}}}
function analyze(){const rows=currentRows();if(!rows.length){state.analysis=[];render();return}state.analysis=A.analyzeCampaignV2(rows,settings());render();if(state.selected){const x=state.analysis.find(v=>v.sku===state.selected);if(x)renderDetail(x)}}
function currentBudget(x){return x.budgetStates?.at(-1)?.code||'BUDGET_STATE_UNCERTAIN'}
function primaryLabel(x){const m=x.regimeMetrics?.at(-1);return m?`${esc(m.primaryKpiName)}: ${fmt(m.primaryMean)}`:'—'}
function recommendationHtml(x){const r=x.recommendation;if(!r)return '—';if(r.status==='RECOMMENDED')return `<span class="badge rec">Target ${cpcMoney(r.targetCpc)}</span><small>${r.direction==='UP'?'↑':'↓'} ${pct(Math.abs(r.stepPct))}</small>`;return `<span class="badge no">NO_FEASIBLE_TEST</span><small>${esc(r.reasonCode||'')}</small>`}
function temporalHtml(t){const q=t.temporal;if(!q)return `<span class="code">UNADJUSTED</span><small>temporal model не применён</small>`;const stable=q.status==='LAG_STABLE',source=t.effectSource==='TEMPORAL_ADJUSTED'?'TEMPORAL_ADJUSTED':(t.effectSource||'UNADJUSTED_DIAGNOSTIC');const lags=(q.lagResults||[]).filter(r=>r.status==='IDENTIFIED').map(r=>`lag ${r.lag}: ${pct(r.adjustedEffectRelative)}`).join(' · ');return `<span class="code">${esc(q.status)}</span><small>lag 0/+1/+2 · ${esc(source)}${lags?` · ${esc(lags)}`:''}${stable?' · stable':''}</small>`}
function uncertaintyHtml(t){const u=t.uncertainty;if(!u||u.status!=='UNCERTAINTY_IDENTIFIED')return `<span class="code">${esc(u?.status||'UNCERTAINTY_NOT_IDENTIFIED')}</span><small>${esc(u?.reason||'bootstrap unavailable')} · ${esc(t.fdrStatus||'FDR_NOT_APPLICABLE')}</small>`;const before=t.decisionBeforeFdr?` · до FDR: ${esc(t.decisionBeforeFdr)}`:'';return `<span class="code">UNCERTAINTY_IDENTIFIED</span><small>CI ${pct(u.ci.low)}…${pct(u.ci.high)} · p=${prob(u.pValue)} · q=${prob(t.qValue)} · ${esc(t.fdrStatus||'FDR_NOT_APPLICABLE')}${before}</small>`}
function render(){const a=state.analysis;$('kpiSku').textContent=a.length;$('kpiRegimes').textContent=a.reduce((s,x)=>s+x.cpcRegimes.length,0);$('kpiClean').textContent=a.reduce((s,x)=>s+x.transitions.filter(t=>t.code==='CLEAN_CPC_TRANSITION').length,0);$('kpiTests').textContent=a.filter(x=>x.recommendation?.status==='RECOMMENDED').length;$('kpiNoTest').textContent=a.filter(x=>x.recommendation?.status==='NO_FEASIBLE_TEST').length;
  $('resultsBody').innerHTML=a.length?a.map(x=>`<tr data-sku="${esc(x.sku)}"><td><strong>${esc(x.sku)}</strong><small>${esc(x.name)}</small></td><td>${cpcMoney(x.currentRegime?.cpcMedian??x.currentRegime?.cpc)}</td><td>${x.cpcRegimes.length}</td><td><span class="code">${esc(currentBudget(x))}</span></td><td>${esc(x.priceStatus)} · ${pct(x.priceCoverage)}</td><td>${x.transitions.length} · clean ${x.transitions.filter(t=>t.code==='CLEAN_CPC_TRANSITION').length}</td><td>${primaryLabel(x)}</td><td><span class="obs">OBSERVATIONAL</span></td><td>${recommendationHtml(x)}</td></tr>`).join(''):'<tr><td colspan="9" class="empty">Нет данных.</td></tr>';
  $('resultsBody').querySelectorAll('tr[data-sku]').forEach(tr=>tr.addEventListener('click',()=>{state.selected=tr.dataset.sku;renderDetail(state.analysis.find(x=>x.sku===state.selected))}))}
function stat(label,value,sub=''){return `<div class="stat"><span>${esc(label)}</span><strong>${value}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function testCard(r){if(r.status!=='RECOMMENDED')return `<div class="test-card no-test"><div class="eyebrow">NO_FEASIBLE_TEST</div><h3>Следующий статистически осмысленный тест не сформирован</h3><p>${esc(r.reason||'Недостаточно evidence.')}</p><code>${esc(r.reasonCode||'')}</code></div>`;const c=r.card;return `<div class="test-card"><div class="test-title"><div><div class="eyebrow">NEXT TEST · OBSERVATIONAL BASIS</div><h3>${cpcMoney(c.baselineAchievedCpc)} → ${cpcMoney(c.targetCpc)}</h3></div><span class="badge rec">${r.direction}</span></div><div class="test-grid">
${stat('Текущий AchievedCPC',cpcMoney(c.baselineAchievedCpc))}${stat('TargetCPC',cpcMoney(c.targetCpc))}${stat('Коридор',`${cpcMoney(c.targetCorridor.low)} – ${cpcMoney(c.targetCorridor.high)}`)}${stat('Мин. separation',pct(c.minSeparation.relative),cpcMoney(c.minSeparation.absolute))}${stat('Мин. полных дней',fmt(c.minFullDays))}${stat('Primary KPI volume',`${fmt(c.requiredPrimaryKpi.value)} · ${esc(c.requiredPrimaryKpi.name)}`)}${stat('Макс. срок',`${fmt(c.maxTestDays)} дн.`)}${stat('Stabilization',`${fmt(c.stabilizationDays)} дн.`)}
</div><div class="test-note"><strong>Stop-loss:</strong> ${esc(c.stopLoss.text)}</div><div class="test-note"><strong>Смешанный тест, если:</strong> ${c.mixedConditions.map(esc).join('; ')}.</div><div class="test-note"><strong>Когда перезагрузить:</strong> ${esc(c.reloadWhen)}</div><div class="test-note"><strong>Возможные решения:</strong> ${c.possibleDecisions.map(x=>`<code>${esc(x)}</code>`).join(' ')}</div></div>`}
function renderDetail(x){if(!x)return;$('detailEmpty').hidden=true;$('detailContent').hidden=false;$('detailTitle').textContent=`SKU ${x.sku}`;$('detailName').textContent=x.name||'';$('detailDecision').innerHTML=`<span class="obs">OBSERVATIONAL</span> ${recommendationHtml(x)}`;const m=x.regimeMetrics.at(-1);$('detailStats').innerHTML=stat('Текущий CPC',cpcMoney(x.currentRegime?.cpcMedian??x.currentRegime?.cpc))+stat('CPC noise',pct(x.cpcNoise),'log-scale robust noise')+stat('Budget',`<span class="code">${esc(currentBudget(x))}</span>`)+stat('Price',esc(x.priceStatus),`coverage ${pct(x.priceCoverage)}`)+stat('Primary KPI',fmt(m?.primaryMean),m?.primaryKpiName||'—')+stat('Order coverage',pct(x.dataQuality.orderReliableCoverage))+stat('Accounting mismatch',fmt(x.dataQuality.accountingMismatchCount));$('testPanel').innerHTML=testCard(x.recommendation);
  const budgetBy=new Map(x.budgetStates.map(b=>[b.regimeId,b]));$('regimeBody').innerHTML=x.regimeMetrics.map(r=>`<tr><td>${esc(r.regimeId)}</td><td>${dateRu(r.startDate)}–${dateRu(r.endDate)}</td><td>${cpcMoney(r.cpc)}</td><td>${r.nDays}</td><td>${esc(r.primaryKpiName)} ${fmt(r.primaryMean)}</td><td><span class="code">${esc(budgetBy.get(r.regimeId)?.code||'UNCERTAIN')}</span></td></tr>`).join('');$('transitionBody').innerHTML=x.transitions.length?x.transitions.map(t=>`<tr><td>${esc(t.fromRegimeId)}→${esc(t.toRegimeId)}</td><td>${cpcMoney(t.fromCpc)}→${cpcMoney(t.toCpc)}</td><td><span class="code">${esc(t.code)}</span></td><td><span class="badge ${t.decision==='DEPLOY'?'rec':t.decision==='ROLLBACK'?'warn':''}">${esc(t.decision||'INCONCLUSIVE')}</span></td><td>${pct(t.effectRelative)}<small>${esc(t.effectSource||'UNADJUSTED_OBSERVATIONAL')}</small></td><td>${temporalHtml(t)}</td><td>${uncertaintyHtml(t)}</td><td><span class="obs">OBSERVATIONAL</span><small>${esc(t.decisionReason||t.reason)}</small></td></tr>`).join(''):'<tr><td colspan="8" class="empty">Устойчивых CPC-переходов не найдено.</td></tr>';$('responsePanel').innerHTML=x.responseCurve.points.length?x.responseCurve.points.map(p=>`<div class="response-point"><span>${cpcMoney(p.cpc)}</span><strong>${fmt(p.primaryMean)}</strong><small>n=${fmt(p.nDays)} · OBSERVATIONAL</small></div>`).join(''):'<div class="empty">Недостаточно чистых переходов для response curve.</div>'}
$('fileInput').addEventListener('change',e=>ingest([...e.target.files]));$('campaignSelect').addEventListener('change',analyze);$('analyzeButton').addEventListener('click',analyze);['mdePct','maxTestDays','minCpcChange','unitContribution','marginPct'].forEach(id=>$(id).addEventListener('change',analyze));
})();
